server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8083/eureka

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: voutcherService
          uri: lb://VOUTCHER-SERVICE
          predicates:
            - Path=/voutcherDeposit/**

        - id: mealService
          uri: lb://MEAL-SERVICE
          predicates:
            - Path=/mealDeposit/**

        - id: webUIService
          uri: lb://WEB-UI-SERVICE
          predicates:
            - Path=/, /home, /index, /**.js
